version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Build and Test project
          command: source ./ci/scripts/build.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
