version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Build and Test project
          command: source ./ci/scripts/build.sh

  test:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Configure bundler
          command: source ./ci/scripts/bundler_config.sh
      - run:
          name: Configure Ruby dependencies
          command: source ./ci/scripts/install_ruby.sh
      - run:
          name: Configure utf-8 locate
          command: source ./ci/scripts/set_locate.sh
      - run:
          name: Configure Fastlane environment variables
          command: source ./ci/scripts/fastlane_config.sh
      - run:
          name: Build and Test project
          command: source ./ci/scripts/test.sh
  
  deploy_develop:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Configure bundler
          command: source ./ci/scripts/bundler_config.sh
      - run:
          name: Install dependencies
          command: source ./ci/scripts/install.sh
      - run:
          name: Configure utf-8 locate
          command: source ./ci/scripts/set_locate.sh
      - run:
          name: Configure Fastlane environment variables
          command: source ./ci/scripts/fastlane_config.sh
      - run:
          name: Configure github
          command: source ./ci/scripts/git_config.sh
      - run:
          name: Build and Test project
          command: source ./ci/scripts/test.sh 
      - run:
          name: Generate changelog, docs, coverage
          command: source ./ci/scripts/deploy_develop.sh
          environment:
            SCRIPT_PATH: ./ci/scripts

  deploy_master:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Configure bundler
          command: source ./ci/scripts/bundler_config.sh
      - run:
          name: Install dependencies
          command: source ./ci/scripts/install.sh
      - run:
          name: Configure utf-8 locate
          command: source ./ci/scripts/set_locate.sh
      - run:
          name: Configure Fastlane environment variables
          command: source ./ci/scripts/fastlane_config.sh
      - run:
          name: Create keychain & Add certificates
          command: source ./ci/scripts/keychain_add.sh
          environment:
            CERTIFICATES_PATH: ./ci/cert
            KEYCHAIN_NAME: ios-app.keychain
      - run:
          name: Configure github
          command: source ./ci/scripts/git_config.sh
      - run:
          name: Master deploy
          command: source ./ci/scripts/deploy_master.sh
      - store_artifacts:
          path: ./$XCODE_SCHEME_DEMO.ipa
      - run:
          name: Remove keychain & certificates
          command: source ./ci/scripts/keychain_remove.sh
          environment:
            KEYCHAIN_NAME: ios-app.keychain
      - run:
          name: Update cocoapods repo
          command: source ./ci/scripts/pod_trunk_push.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          filters:
            branches:
              ignore: 
                - develop
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: 
                - develop
      - deploy_master:
          requires:
            - test
          filters:
            branches:
              only: 
                - master
